# Generated by Django 4.1.7 on 2023-03-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadospessoais',
            options={'verbose_name': 'Dados Pessoais', 'verbose_name_plural': 'Dados Pessoais'},
        ),
    ]
